.github/workflows/mac.yml
.github/workflows/ubuntu.yml
.github/workflows/win.yml
README.md
test/static-thread-pool.cc

In this PR I created .github/workflows directory, which contains 3 .yml files
for having workflows on macOS, Ubuntu and Windows. Then I updated README.md 
in the root directory in order to have the status of the last build of eventuals lib, libuv, 
tests and running tests. Then I also updated /test/static-thread-pool.cc in order to
make Schedulable test depending on the number of cores supported by the 
implementation.

Github Actions + Schedulable test fix

---

BUILD.bazel
stout/take.h
test/BUILD.bazel
test/take.cc

Adding a new API to get values from streams.
usage example:
`Iterate(container) 
| TakeFirstN(5)
| Collect<std::set<int>()
...`
`Stream<int>()... 
| TakeRange(3, 10) // 3 - start position, 10 - amount of elements to get from the stream
| Loop<int>()
...`
`Iterate(container) 
| TakeLastN(5)
| Collect<std::set<int>()
...`

Add TakeFirstN, TakeRange, TakeLastN API for the streams

---

test/filter.cc

Fix Filter.OddMapCollectFlow test on Windows

---

.github/workflows/check_format_code.yml
.github/workflows/macos.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml

For now this checks will be triggered on any push on any branch.

Make `Build` and `Test` checks triggered

---

README.md

Since the `commit` hash and `shallow_since` options were updated, we need also
to update `Usage` section in `README.md` file.

Update `Usage` section

---

eventuals/generator.h
eventuals/iterate.h
test/generator.cc

Allows passing some values to `Generator` to produce new ones.

Add support of `Generator<From, To>`

---

eventuals/do-all.h
test/do-all.cc

For now `Succeed` test is ready for your review. Soon I will prepare `Fail` and `Interrupt` tests too.

Refactor `DoAll` for more ergonomic use

---

.github/workflows/nobuild.yml

Fix doc-only PRs by providing dummy build results.

---

eventuals/concurrent-ordered.h
eventuals/do-all.h
eventuals/pipe.h
test/concurrent.h

Add missing #pragma once

---

BUILD.bazel
README.md
eventuals/if.h
eventuals/then.h
test/BUILD.bazel
test/if.cc

Add documentation on errors and error handling

---

README.md

This section intentionally left blank.

Update documentation to reflect the code

---

test/http-mock-server.h
test/http.cc

Fix race condition in HttpMockServer

---

eventuals/event-loop.cc
eventuals/event-loop.h
eventuals/http.h
eventuals/lock.h
eventuals/scheduler.h
eventuals/static-thread-pool.h
eventuals/stream.h
test/http-mock-server.h
test/http.cc

Otherwise it's possible that we'll have race conditions.

Ensure event loop eventuals always execute in the event loop

---

eventuals/task.h
test/task.cc

This reverts commit 623bd65e97392d487877dfbc89f693ddddd6175c.
This breaks eventuals-grpc due to not supporting references as the
'To' argument. We didn't think we needed that but we do!

Revert "Optimize away heap allocation from `Task` synchronous helpers"

---

eventuals/if.h
test/if.cc
test/lock.cc

Rename '.then()' and '.otherwise()' for 'If()' to '.yes()' and '.no()'

---

.github/workflows/build_and_test.yml

Need to set this to -1 so that we get output from GitHub Workflows.

Set 'experimental_ui_max_stdouterr_bytes'

---

eventuals/http.h

Fix new-delete-type-mismatch error caught by asan

---

eventuals/rsa.h

RSAPrivateKey_dup returns an RSA object which must be freed after use.
Fixes https://github.com/3rdparty/eventuals/issues/219.

Fix memory leak in rsa::Key::Copy

---

.github/workflows/build_and_test.yml

NOTE: we'll need to update our build rules in settings before this will be able to be merged.

Turn on --config=asan for GitHub Workflow

---

eventuals/expected.h
test/do-all.cc

Minor code cleanups and reformatting

---

eventuals/catch.h
test/eventual.cc

Ensure we don't use 'Undefined' as a continuation for 'Catch'

---

.bazelrc
.github/workflows/build_and_test.yml

Try to minimize paths for bazel output files

---

eventuals/scheduler.h

I noticed that we had a `CHECK()` failure on one of the last tests which was surprising, so I've added some more `CHECK_NOTNULL()` to see if we can crack down on how/where this is coming from.

Add 'CHECK_NOTNULL()' for safety

---

protoc-gen-eventuals/templates/eventuals.cc.j2
protoc-gen-eventuals/templates/eventuals.h.j2

This is missing tests because all of the generated code is missing tests at this point in time.

Add necessary 'Raises<std::exception>' for protoc-gen-eventuals generated code

---

.github/workflows/build_and_test.yml
.github/workflows/check_code_style.yml

See https://github.com/mxschmitt/action-tmate#manually-triggered-debug
Fixes https://github.com/3rdparty/eventuals/issues/283

Make tmake debugging opt-in for faster failures

---

eventuals/eventual.h
eventuals/expected.h
eventuals/generator.h
eventuals/loop.h
eventuals/stream.h
eventuals/task.h
eventuals/type-traits.h
test/type-traits.cc

The helper checks if every type in a tuple is contained in another
tuple OR is derived from one of the types in the other tuple.

Add new helper to `type-traits`

---

.github/workflows/build_and_test.yml
3rdparty/stout-borrowed-ptr/repos.bzl
BUILD.bazel
eventuals/event-loop.h
eventuals/static-thread-pool.h

More borrowing added for `StaticThreadPool` and `EventLoop` types.

Add more borrowing

---

.dazelrc

Also added a comment explaining why we picked the directory we did and why it's best effort.

Use a different directory for Bazel caching

---

test/BUILD.bazel
test/eventual.cc
test/just.cc

Add tests for a void argument.

Move Just() tests into a separate file

---

.bazelrc
.github/workflows/build_and_test.yml

Refer to issue https://github.com/reboot-dev/company/issues/71

Google remote cache to work in read-only mode from local workstations

---

eventuals/concurrent.h
eventuals/event-loop.cc
eventuals/event-loop.h
eventuals/executor.h
eventuals/flat-map.h
eventuals/http.h
eventuals/lock.h
eventuals/range.h
eventuals/repeat.h
eventuals/scheduler.cc
eventuals/scheduler.h
eventuals/static-thread-pool.cc
eventuals/static-thread-pool.h
eventuals/stream.h
eventuals/take.h
eventuals/task.h
test/grpc/death-client.cc
test/grpc/death-server.cc
test/http.cc
test/signal.cc
test/static-thread-pool.cc

Make 'Scheduler::Context' be borrowable

---

.gitmodules
bazel/deps.bzl
bazel/repos.bzl
bazel/submodules.bzl
eventuals/BUILD.bazel
eventuals/event-loop.h
eventuals/executor.h
eventuals/grpc/BUILD.bazel
eventuals/grpc/client.h
eventuals/grpc/completion-pool.h
eventuals/grpc/server.h
eventuals/scheduler.h
eventuals/static-thread-pool.h
test/callback.cc

Update eventuals to match the latest 'stout'

---

eventuals/event-loop.h
eventuals/executor.h
eventuals/grpc/client.h
eventuals/grpc/completion-pool.h
eventuals/grpc/server.h
eventuals/scheduler.h
eventuals/static-thread-pool.h
test/callback.cc

Update to new header file names to match rename in
https://github.com/3rdparty/stout/pull/44

Manually update to latest `stout`

---

Dockerfile.dazel

See more: https://github.com/bazelbuild/bazel/issues/15558#issuecomment-1136150886

Fix Dazel build

---

.dazelrc
protoc-gen-eventuals/protoc-gen-eventuals.py

This should hopefully fix the code style errors being flagged in #409.

Autoformat python files: unblock dev-tools update

---

eventuals/BUILD.bazel
eventuals/compose.h
eventuals/expected.h
eventuals/finally.h
eventuals/grpc/server.h
eventuals/rsa.h
eventuals/x509.h
test/catch.cc
test/expected.cc
test/finally.cc
test/grpc/server-death-test.cc

Use the C++23 proposed 'std::expected' instead of our own.

Replace 'Expected' with 'tl::expected'

---

eventuals/grpc/server.cc
eventuals/grpc/server.h

Progress towards https://github.com/reboot-dev/respect/issues/606.

Make max gRPC message size configurable

---

eventuals/event-loop.h

IMHO, it's easier to read `if` than `if not`.

Refactor #ifdef for better readability

---

test/BUILD.bazel
test/concurrent/BUILD.bazel
test/grpc/BUILD.bazel

Inspired on [`this`](https://github.com/3rdparty/eventuals/pull/460) PR!

Extracting a separate library for 'backward' stuff

---

bazel/deps.bzl
bazel/repos.bzl
eventuals/BUILD.bazel
eventuals/collect.h
test/collect.cc

Add support for google::protobuf::Repeated(Ptr)Field in Collect()

---

eventuals/BUILD.bazel
eventuals/control-loop.h
eventuals/executor.h
test/BUILD.bazel
test/control-loop.cc

This PR adds a new abstraction called 'ControlLoop'. It is
basically just a piece of code that is for ever running and
doing some kind of computation for us.

Introduce 'ControlLoop'

---

eventuals/BUILD.bazel
eventuals/notification.h
test/BUILD.bazel
test/notification.cc

This is similar to 'absl::Notification', except with less functions (for now, we can add more later) and built to work with eventuals.

Introduce 'Notification' abstraction

---

eventuals/grpc/client.h
test/grpc/BUILD.bazel
test/grpc/client-interruptible.cc

With this commit the grpc client can now be interrupted.

Make Client interruptable

---

eventuals/catch.h
eventuals/grpc/server.cc

In general, it's never safe to use any members of a continuation after
calling into it's continuation 'k_', but we can still use stack
variables.
Also added a TODO uncovered as part of debugging.

Fix heap-after-use bug in 'Catch'

---

eventuals/concurrent.h

ASAN found [this](https://github.com/3rdparty/eventuals/runs/7944786807?check_suite_focus=true).

Fix heap-after-use bug in 'Concurrent'

---

eventuals/pipe.h
test/pipe.cc

Clarify the state of the pipe during unit tests.

Document `Pipe` methods and unit tests

---

eventuals/pipe.h
test/pipe.cc

This allows unit tests to wait for all work in a pipe to be processed
before doing things like asserting on results.

Add `Pipe::WaitForClosedAndEmpty()`

---

Dockerfile.dazel
eventuals/BUILD.bazel
eventuals/fork-join.h
eventuals/lock.h
eventuals/pipe.h
eventuals/promisify.h
eventuals/static-thread-pool.h
test/BUILD.bazel
test/do-all.cc
test/fork-join.cc
test/static-thread-pool.cc

Also fixes a bug discovered when waiting on a `ConditionVariable`.

Introduce 'ForkJoin()' and 'StaticThreadPool::ForkJoin()' combinators
