stout/callback.h
Fix for "std doesn't have a function called move" error in callback.h.
=> Fix Linux and Windows builds

tools/bootstrap
On some platforms shell is symlinked to dash and it doesn't support double
brackets. Bash should be enough for bootstrap to work fine on most systems.
=> Use bash instead of shell for tools/bootstrap

stout/iterate.h
While using Iterate with std::array there 'i' variable at lambda and i is int now, so there are a lot of warnings about comparison std::array.size -> size_t and i -> int
=> Fix compilation warnings while using Iterate with std::array

BUILD.bazel, stout/filter.h, test/BUILD.bazel, test/filter.cc
New Filter eventual, that takes some lambda function F that split values from the previous stream.
Example of usage:
`Iterate(v)
|    Filter([](int x){ return x % 2 == 0; })
|    Collect<std::vector<int>>()
...`
All odd numbers will appear at vector after Collect
=> Add Filter wrapper Interface

bazel/deps.bzl, bazel/repos.bzl
Right now we are checking by ourselves if a certain rule already exists. There's a [maybe](https://docs.bazel.build/versions/main/repo/utils.html#maybe) rule inside bazel which does exactly the same. Why make our own bicycle if we have an already built one inside bazel?
=> Change ifs to maybe in bazel files

stout/event-loop.cc, stout/event-loop.h, stout/signal.h, test/BUILD.bazel
1. This PR adds a RAII implementation for signals inside the EventLoop to ensure the correct behavior.
Due to the design choices in libuv the handle is now allocated on heap and there's an added EventLoop::CloseCallback method which is called on the next iteration of uv_run to ensure de-allocation.
2. Added a check in EventLoop::~EventLoop to ensure that uv_close function returns 0 and not UV_EBUSY value or any other incorrect value.
=> Fix Signal implementation and re-enable tests

stout/event-loop.h, test/BUILD.bazel
This PR adds a RAII implementation for timers inside the EventLoop to ensure the correct behavior.
Due to the design choices in libuv the handle is now allocated on heap and is using an EventLoop::CloseCallback method which is called on the next iteration of uv_run to ensure de-allocation.
=> Fix Timer implementation and re-enable tests

.github/workflows/check_format_code.yml, test/parallel.cc
This .yml file helps to verify that a repo's formatting matches our
specifications (.clang-format file in the root directory), but doesn't
automatically fix any issues.
For now I need to figure out how to make this action automatically
check if every line of the code exceeds 80 characters and make it work
with BUILD.bazel and WORKSPACE.bazel files.
=> Added check_format_code.yml

BUILD.bazel, test/BUILD.bazel
=> Refactor library into sub-libraries eventuals-events and eventuals-http and only build eventuals-http on macOS and Linux

BUILD.bazel, stout/range.h, test/BUILD.bazel, test/range.cc
`Range` interface gives the stream that iterates through the sequence of given ints.
Examples:
```
Range(10, 20)
| Map(Then([](int x){ return x + 5; }))
| Collect<std::vector<int>>
```
=> Add Range streaming Interface

.github/workflows/windows.yml
We do not need to run this task cause there was an update. Use the link below
to see it:
https://github.com/actions/virtual-environments/commit/a908240ead0632d98143582e0cdea014ee28629f (images/win/Windows2019-Readme.md Line 18)
=> Remove `Install LLVM and Clang` task on Windows

test/dns-resolver.cc
Helps improving test times and, generally speaking, we don't want to rely on external hosts in tests.
=> Stop relying on google.com in dns tests

test/timer.cc
Test crashes that we've seen as recorded in #57 and [here](https://github.com/3rdparty/stout-eventuals/pull/72/checks?check_run_id=3764191052) and [here](https://github.com/3rdparty/stout-eventuals/pull/72/checks?check_run_id=3764191055) can be traced back to `EventLoopTest.InterruptTimer` being the previous test that ran. After investigating we noticed that `EventLoopTest.InterruptTimer` has a thread that has references to memory on the stack that might go out of scope because the thread was detached. This PR resolves #57 by ensuring that the thread has completed before the stack gets destructed and deallocated.
=> Fix bug in test where thread might use deallocated memory

test/dns-resolver.cc
DNS Fail test with 'localhost1' set as an address runs for 2-6 seconds depending on the machine. This commit fixes the issue with that particular test.
=> Lower time duration of DNS Fail test on Windows

stout/event-loop.cc, stout/event-loop.h, test/event-loop-test.h
Currently you can "accidently" write a test which uses the default
event loop without properly extending from
'EventLoopTest'. Unfortunatly this means that if a previous test
didn't properly destruct the event loop (e.g., because it failed or
the test has a bug) then you may run into undefined state. In order to
make sure that everyone has a well-defined event loop they must extend
from 'EventLoopTest' and by ensuring that there is no default event
loop to start then a test that doesn't extend from 'EventLoopTest' (or
reset the default event loop on their own) will crash.
=> Clear default event loop before running tests

BUILD.bazel, stout/event-loop.cc, stout/event-loop.h, stout/let.h, stout/timer.h, test/BUILD.bazel, test/let.cc
'Let()' provides syntactic sugar for using a 'Closure()' when you
effectively want to introduce a binding that will persist within the
enclosing scope.
=> Introduce 'Let'

stout/iterate.h, test/iterate.cc
Allows use Iterate interface with `std::initializer_list` as argument:
```
...
return Iterate({1,2,3})
| Collect<std::vector<int>>();
...
```
=> Add support of std::initializer_list for Iterate

BUILD.bazel, stout/range.h, stout/stream-for-each.h, test/BUILD.bazel, test/stream-for-each.cc
`StreamForEach` is an instance that provides to create streams with inner loops
Let's imagine that a single common stream represents a one-level loop like
`Range(n)`  equals to `for (int i =0; i < n; ++i){...}`
When there is a composition of that Range with `StreamForEach([](int x) { return Range(k); })` it equals to 
```
for (int i = 0; i < n; ++i)
{
for (int j = 0; k < 2; ++k){...}
}
```
In other words - it adds the inner loop inside the loop above each time you compose it with `StreamForEach`
The idea - pass a `Lamda` to the `StreamForEach` that produces a `Stream` instance (for now it instance that inherits from `TypeErasedStream` structure) and this `Stream` will be the inner loop for the stream above.
=> Add 'StreamForEach' interface

BUILD.bazel, stout/os.h, stout/static-thread-pool.cc
This PR makes so that each thread in static thread pool is mapped to a specific core which is determined by the position of a particular thread inside vector.
=> Pin threads to specific cores

BUILD.bazel, stout/http.cc, stout/http.h, test/BUILD.bazel, test/http.cc
This PR introduces Get and Post methods to allow us make http requests to some specific URL. 
There are two crucial structures:
1. `PostFields` is simply a vector of pairs of string and string - the first one being the key and the second one being the value.
Here's an example of how to instantiate it:
```
PostFields fields = {
{"title", "test"},
{"body", "message"}};
```
2. `Response` is a return result of Get and Post methods. It has 2 public fields: `code` and `body`. They can be used later just like this:
```
Get("http://example.com") 
| Then([](auto&& response){
do_smth_with_code(response.code);
do_smth_with_body(response.body);
});
```
=> Implement http::Get and http::Post methods

BUILD.bazel, eventuals/do-all.h, test/BUILD.bazel, test/do-all.cc
Basically `DoAll()` takes a variadic list of eventuals, terminate them, store
them in a `std::tuple`, call `Start()` on all them, wait for them all to be
done, and then continue with a tuple of results from each of the eventuals
passed in. Each result may be either a result from eventual or `std::exception`.
=> Introduce `DoAll()` implementation

bazel/repos.bzl, eventuals/task.h, test/task.cc
Allows users to capture some values from the previous eventuals before `Task<...>`
=> Add support of `Task<From_, To_>`

eventuals/event-loop.h, eventuals/signal.h, test/signal.cc
The current helpers for signal handling are relatively low-level as
they were designed to wrap the low-level 'uv_signal*()' family of
functions. In practice we often want to be able to specify multiple
signals and find out which signal was raised; this commit introduces
the helper 'WaitForSignal()' which does just that.
=> Introduce 'WaitForSignal()'

BUILD.bazel, eventuals/transformer.h, test/BUILD.bazel, test/transformer.cc
`Transformer` is a type-erased that basically allows transforming return types of eventual during the work.
Pseudo-code:
```
Stream(<type From>)
| Transformer<<type From>, <type To>>("transformer labmda")
| Other stuff that takes <type To>
```
=> Introduce `Transformer`

BUILD.bazel, eventuals/pipe.h, test/BUILD.bazel, test/pipe.cc
`Pipe` class implements a synchronized queue. It is generic and contains
`std::deque<t> values_`. This class is inherited from `Synchronizable`
(`eventuals/lock.h`).
=> Introduce `Pipe` class

BUILD.bazel, eventuals/concurrent-ordered.h, eventuals/flat-map.h, test/concurrent.cc
`ConcurrentOrdered` sorts values from `Concurrent` in order that it takes from a stream before.
=> Introduce `ConcurrentOrdered`

.github/workflows/ubuntu.yml
We wanna remove this part of code. Check [this](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md) link. They've updated repo, so on Ubuntu 20.04 we already have preinstalled Clang. That's why ` KyleMayes/install-llvm-action` is already not relevant for us.
=> Remove redundant code

.github/workflows/macos.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml
Changelists that only affect markdown files shouldn't affect the result
of any builds or tests: skip build-and-test actions on commits that only
touch markdown files.
This should vastly reduce the time it takes to merge documentation PRs
into main, and it will also avoid wasting compute running tests on no-op
commits.
This change was inspired by tests running for 30 minutes on the
markdown-only change https://github.com/3rdparty/eventuals/pull/165
which both delayed submission and wasted compute resources.
=> Skip build-and-test hooks for markdown commits

README.md, eventuals/lock.h, eventuals/pipe.h, test/lock.cc
While we previously had support for a kind of condition variable via
'Wait()' their syntax was low-level. This commit introduces a
higher-level abstraction that is very similar to condition variables
in higher-level languages.
=> Introduce 'ConditionVariable'

.github/workflows/check_code_style.yml
We should be sure that before running all checks for code style we have clang-format installed, and if yes, we recreate a symlink to the correct version of clang-format in order to start checking all files style with correct clang-format version.
=> Configure clang-format before running checks for code style

eventuals/builder.h, eventuals/http.h, test/http.cc
Please use [RFC 7230, section 3.2.2](https://www.rfc-editor.org/rfc/rfc7230.html#section-3.2.2) to fully understand the changes made in this PR!
=> Use std::map as a return value for Response::headers()

.github/workflows/build_and_test.yml, .github/workflows/check_code_style.yml
Now the strategy is that build action will trigger on every
pull request and on any push to `main` branch. Thus there will
not be duplicate workflows.
=> Add pull_request trigger for GitHub action

eventuals/lock.h
Having access to the underlying lock makes it easier to do the
`Acquire`/`Release` dance around the ConditionVariable's `Wait` method.
=> Expose ConditionVariable lock

.github/workflows/build_and_test.yml, .github/workflows/check_code_style.yml
We've transferred all preparations like creating symlink
to dev-tools/check-code-style/action.yml to simplify the
code style caller (check_code_style.yml).
=> Simplify caller's logic for code style checks

.gitmodules, eventuals/lock.h, test/lock.cc
Before this commit a `Waiter` was added to the pending list of waiters no matter if they were done waiting or not, potentially leading to a use-after-free error.
Bonus commit: The PR contains an extra commit to add a `branch = main` to the `dev-tools` submodule.
=> Fix bug in condition variable's waiters

.bazelrc
Similar to reboot-dev/respect#70, this adds a --config=asan build mode to eventuals-grpc.
It updates the dev-tools submodule to get the latest changes to .bazelrc which create the asan config.
=> Add asan to eventuals via dev-tools

eventuals/catch.h, eventuals/closure.h, eventuals/concurrent-ordered.h, eventuals/concurrent.h, eventuals/conditional.h, eventuals/do-all.h, eventuals/event-loop.h, eventuals/eventual.h, eventuals/filter.h, eventuals/flat-map.h, eventuals/generator.h, eventuals/head.h, eventuals/http.h, eventuals/if.h, eventuals/lock.h, eventuals/loop.h, eventuals/map.h, eventuals/raise.h, eventuals/range.h, eventuals/reduce.h, eventuals/repeat.h, eventuals/scheduler.h, eventuals/static-thread-pool.h, eventuals/stream.h, eventuals/take.h, eventuals/task.h, eventuals/then.h, eventuals/transformer.h, eventuals/until.h
By always storing 'k_' as the _last_ member it will be destructed
_first_ and thus we won't have any use-after-delete issues during
destruction of 'k_' if it holds any references or pointers to any (or
within any) of the previous continuations.
This fixes 3rdparty/eventuals-grpc#71 and allows us to turn on
building with 'asan' on this repository as well as eventuals-grpc.
=> Reorder eventuals continuation 'k_' to be last

eventuals/terminal.h
@while-false this was inspired from our debugging session, will possibly help track down issues even before pulling out the debugger.
=> Log warning to help debug when dereferencing an eventual that fails

eventuals/rsa.h, eventuals/x509.h
If these methods are not inlined, they'll cause "duplicate definition"
errors when used in a program that has multiple translation units.
TESTED: caused build failures in upcoming `reboot-dev/respect` change
previously, build failures now resolved.
=> Inline a few header methods

.github/workflows/build_and_test.yml, .gitignore, Dockerfile.dazel, WORKSPACE
Before this PR the `eventuals` repo could only build if you had (the
right version of) `bazel` installed on your machine. To be more hermetic
we'd like to avoid this hope-you-installed-it-right type situations. In
fact, our GitHub Codespaces don't (currently) install `bazel` at all!
This PR adds a symlink to our standard `Dockerfile.dazel` in
the `dev-tools` subrepo, allowing us to use `dazel` to build in a
repeatable way. Dazel will, unfortunately, look for a `WORKSPACE` file
instead of a `WORKSPACE.dazel` file, so we add a symlink to that also.
This is a step towards https://github.com/reboot-dev/company/issues/34
=> Add Dazel configuration

eventuals/compose.h, eventuals/dns-resolver.h, eventuals/eventual.h, eventuals/expected.h, eventuals/filesystem.h, eventuals/raise.h, eventuals/rsa.h, eventuals/task.h, eventuals/then.h, eventuals/type-traits.h, eventuals/x509.h, test/BUILD.bazel, test/concurrent-downstream-done-one-eventual-fail.cc, test/concurrent-emit-fail-interrupt.cc, test/concurrent-fail-before-start.cc, test/concurrent-fail-or-stop.cc, test/concurrent-fail.cc, test/concurrent-interrupt-fail-or-stop.cc, test/concurrent-interrupt-fail.cc, test/conditional.cc, test/do-all.cc, test/eventual.cc, test/expected.cc, test/generator.cc, test/lock.cc, test/repeat.cc, test/task.cc, test/then.cc, test/transformer.cc, test/type-traits.cc
Previously there was no way to know, or track, what errors might
propagate through a an eventual pipeline. This commit introduces the
initial components necessary to do that.
Next step is to add 'ErrorsFrom' to all eventual types and then update
'Composed' to not use 'ErrorsFromComposed' but instead assume that all
eventuals that are composed 'HaveErrorsFrom'.
=> Introduce initial support for "static" errors

test/BUILD.bazel
Not sure what happened while I was away, but still...
Trying to run concurrent tests while commenting everything out (Windows):
Before the fix:
After the fix:
=> Fix concurrent tests

.dazelrc, .github/workflows/build_and_test.yml
Modified pipeline to use remote cache located in Google Cloud Storage with Google credentials.
Google credentials are stored in GitHub organization secrets.
=> Add remote cache support

WORKSPACE.bazel, bazel/deps.bzl, bazel/repos.bzl
This pulled in a newer version of rules_python (through an implicit
dependency via gRPC, which I don't like) which required porting off of
the `pip_import` rule which was deprecated in release 0.1.0 in Oct 2020
(!): https://github.com/bazelbuild/rules_python/releases/tag/0.1.0 and
deleted in release 0.6.0 in Jan 2022:
https://github.com/bazelbuild/rules_python/releases/tag/0.6.0.
This removes the need to depend on a 1-year old absl library (!).
It also unbreaks bazel 5.0: fixes https://github.com/3rdparty/eventuals-grpc/issues/65.
=> Update from gRPC 1.40.0 to 1.45.0-pre1

.bazeliskrc
Bazel 5 used to generate build errors on our code:
https://github.com/3rdparty/eventuals-grpc/issues/65
but that was fixed with a newer gRPC release:
https://github.com/3rdparty/eventuals/pull/247
=> Update to bazel 5.0.0

eventuals/event-loop.h
Notice how in EventLoop::Clock::Timer we are using std::move on const reference, lol!
=> Use move semantic for Timer's methods

eventuals/filter.h, eventuals/range.h, eventuals/repeat.h, eventuals/take.h, eventuals/until.h
Not testable now. Will add tests when other eventual would be up with `ErrorsFrom`.
=> Add `ErrorsFrom` for simple eventuals that just propagate received errors

.github/workflows/build_and_test.yml
Seems like we missed using the remote cache for testing which is actually where most of the building takes place (since eventuals is primarily a header library, but even if it was not, we still want to use the cache for building the tests).
=> Also use remote cache when we test

test/BUILD.bazel
This increases parallelization of test runs (sequential runs consume
each other's timeouts, whereas parallel tests have independent timeouts)
while still guaranteeing varied coverage of random test seeds.
See discussion on https://github.com/3rdparty/eventuals/issues/271
Speeds up tests by 2-5x (2x on average).
TESTED= `dazel test -c dbg --config=asan --spawn_strategy=local --strip="never" //test:grpc --test_arg=--gtest_shuffle --test_arg=--gtest_repeat=100 --runs_per_test=10`
Before:
```
INFO: Build completed, 1 test FAILED, 11 total actions
//test:grpc.   TIMEOUT in 10 out of 10 in 60.1s
Stats over 10 runs: max = 60.1s, min = 60.1s, avg = 60.1s, dev = 0.0s
```
After:
```
INFO: Build completed successfully, 51 total actions
//test:grpc.   PASSED in 41.1s
Stats over 50 runs: max = 41.1s, …
```
=> Shard //test:grpc to fix test timeouts

bazel/repos.bzl
Prefer stable releases over pre-release releases.
=> Use the new gRPC 1.45.0 release

.dazelrc, Makefile
Add a `Makefile` that implements a `make test` command which runs dazel
using a remote build cache.
The cache lives on Google Cloud Compute storage, so it requires a
pre-build authorization step that's awkward for users to run manually.
`make test` prompts users for authorization as needed.
On my fresh GitHub Codespace (where I've never run eventuals) this
reduces build / test time to just a couple of minutes.
=> Add a `make test` command that uses a build cache

.gitmodules, WORKSPACE.bazel
Fixes https://github.com/3rdparty/eventuals/issues/276
=> Add pyprotoc-plugin as a submodule

eventuals/grpc/server.cc, eventuals/grpc/server.h, eventuals/task.h, test/helloworld.eventuals.cc, test/helloworld.eventuals.h
Before this PR the static assert in `task.h` that checks that a given
`Task` only raises the errors specified in its `::Raises` clause didn't
accommodate the possiblity of specifying `::Raises<std::exception>` as
a catch-all.
This PR makes it possible to use that catch-all, allowing us to modify
`server.h` and `server.cc` to match the `std::exception` currently being
raised by generated code.
Fixes https://github.com/3rdparty/eventuals/issues/289
Tested: built `reboot-dev/respect:respect-object-store.tar`.
=> Improve too-constraining static assert.

eventuals/expected.h, test/expected.cc
This allows for explicit checks of `Expected::Of`s for whether the instance has a value of not instead of relying on the less explicit cast to bool.
=> Add explicit `has_value` method

.dazelrc
Progress towards https://github.com/reboot-dev/respect-integration/issues/142
=> Use a custom dazel name to avoid name collisions

BUILD.bazel, eventuals/event-loop.h, test/timer.cc
@ArthurBandaryk this is what we need to do throughout the code base, let me know if you have any questions!
=> Use 'borrowed_callable' to ensure safe use of timers

bazel/deps.bzl, bazel/repos.bzl, test/BUILD.bazel, test/sample_service.proto
Fixes https://github.com/3rdparty/eventuals/issues/291
As expected, this catches when backwards-incompatible code-gen updates
(like https://github.com/reboot-dev/pyprotoc-plugin/commit/ad976383919a1d96e6d1e6a2c86c0ff95623c8ee)
fail to compile. Nice!
=> Add basic compilation tests for generated code

.github/workflows/build_and_test.yml
Before this commit we used a string which required users to know they needed to add `true` or `false` and instead a typed input should make this more user friendly.
=> Use typed input for enabling tmate debugging

eventuals/compose.h, eventuals/then.h
Should be merged after [PR](https://github.com/3rdparty/eventuals/pull/286)
=> Remove defaul `std::exception` if eventual has no `ErrorsFrom`

.github/workflows/build_and_test.yml
GitHub renders the checkbox to the left of the description text which makes the colon useless. But more importantly, we probably shouldn't rely on the rendering in case they change it in the future!
=> Remove useless colon

.dazelrc
Perhaps we'll need to add this in the future if/when we create images and specifically want to use a Docker that is outside of the running Dazel container, but for now we're removing this so that it doesn't cause an unexpected bug or send people in the wrong direction when debugging.
=> Remove unnecessary DAZEL_VOLUMES

eventuals/eventual.h
Explicit names are more self-documenting than omitting unused template
argument names.
=> Prefer explicit typename arg names

test/grpc/BUILD.bazel
This was a workaround for https://github.com/grpc/grpc/issues/13856
which has since been resolved.
=> Remove unneeded `linkstatic`

eventuals/generator.h, eventuals/if.h, eventuals/map.h, eventuals/repeat.h, eventuals/task.h, eventuals/transformer.h, test/if.cc, test/lock.cc
Because most folks are not as used to expression based langauges they
run into issues where they end up doing things in the same eventuals
pipeline expression that they weren't expecting because they were
thinking like it was multiple statements. This is true of 'If.yes()'
and 'If.no()'. By making these take callables (e.g., a lambda) instead
then they are forced to treat the bodies of each not as expressions
and thus will be required to think (a little more) about how to
'std::move()' or copy values.
=> Use callables instead of eventuals for 'If.yes()' and 'If.no()'

test/grpc/server-death-test.cc
We think this fixes #274 which we think is caused by the client
attempting to write a request after the server has already exited.
This commit ensures that `call.Finish()` is called whether or not the
client's write succeeds.
=> Handle write errors in ServerDeathTest

eventuals/BUILD.bazel, eventuals/concurrent.h, eventuals/executor.h, eventuals/generator.h, eventuals/just.h, eventuals/pipe.h, eventuals/task.h, eventuals/transformer.h, test/BUILD.bazel, test/executor.cc
See all commits as some clean up commits along the way.
=> Introduce an 'Executor' for "fire and forget" tasks

test/grpc/BUILD.bazel, test/grpc/client-death-test.cc, test/grpc/death-client.cc, test/grpc/death-constants.h, test/grpc/death-server.cc, test/grpc/server-death-test.cc
Use cross-platform standard C++ to run subprocesses. This is an
incremental fix for building and running tests on windows. It also
avoids warnings emitted by `ASSERT_DEATH` caused by `fork()`-ing from a
multithreaded process.
Fixes #337.
=> Use standard C++ to run subprocesses: avoid posix

test/signal.cc, test/static-thread-pool.cc
In addition to being unused, these are discouraged by the style guide:
https://google.github.io/styleguide/cppguide.html#Namespaces
=> Remove unused using-directives

test/BUILD.bazel, test/http-mock-server.cc, test/http-mock-server.h
By defining a separate library for this helper, we're forced to make
`http-mock-server.h` self-contained (which is also required by the style
guide: https://google.github.io/styleguide/cppguide.html#Self_contained_Headers).
=> Move most of HttpMockSever into a .cc file

test/grpc/accept.cc, test/grpc/build-and-start.cc, test/grpc/cancelled-by-client.cc, test/grpc/cancelled-by-server.cc, test/grpc/client-death-test.cc, test/grpc/deadline.cc, test/grpc/greeter-server.cc, test/grpc/main.cc, test/grpc/multiple-hosts.cc, test/grpc/server-death-test.cc, test/grpc/server-unavailable.cc, test/grpc/streaming.cc, test/grpc/test.h, test/grpc/unary.cc, test/grpc/unimplemented.cc
https://github.com/3rdparty/eventuals/pull/339 removed all uses of
`ASSERT_DEATH`. Tests no longer create detached threads (tests which
create threads now explicitly `join` those threads) so we no longer need
a test fixture to handle thread joining.
=> Remove EventualsGrpcTest: it's unneeded after #339

.mergequeue/config.yml
As discussed in https://app.shortwave.com/m/msg-53b73f1b-66d7-4055-8402-b2aeb69f0bca MergeQueue currently can't accept configurations with `null` values in them. Removing them is the appropriate fix.
=> Remove null values from MergeQueue config

eventuals/x509.h
=> Include rsa.h after all openssl includes

test/concurrent/BUILD.bazel
The reason is simple: glob will never tell you the errors with the filenames that it encountered, while explicit statement will.
=> Explicitly state which files to use as a source in test/concurrent/BUILD.bazel

eventuals/grpc/server.h
This makes it easier to print bad status messages in tests, so we can
change:
`ASSERT_TRUE(status.ok());`
to:
`ASSERT_TRUE(status.ok()) << status;`
This follows the pattern used by `::absl::Status`:
https://github.com/abseil/abseil-cpp/blob/master/absl/status/status.cc#L316-L319
Note that this is dissimilar to `::grpc::Status` which provides no such
convenience functions:
https://grpc.github.io/grpc/cpp/classgrpc_1_1_status.html
=> Add ServerStatus.ToString() and operator<<

test/grpc/accept.cc, test/grpc/build-and-start.cc, test/grpc/cancelled-by-client.cc, test/grpc/cancelled-by-server.cc, test/grpc/client-death-test.cc, test/grpc/deadline.cc, test/grpc/greeter-server.cc, test/grpc/multiple-hosts.cc, test/grpc/streaming.cc, test/grpc/unary.cc, test/grpc/unimplemented.cc
When a status is unexpectedly OK, it's easier to debug the problem when
the failure messages includes more details about the bad status.
=> Print bad status details on `ASSERT_TRUE(status)`

eventuals/event-loop.h, eventuals/http.h
Fixes the following error:
```
[ RUN      ] Schemes/HttpTest.GetHeaders/1
F20220428 16:15:13.547349 665984512 http.h:1059] Check failed: curl_easy_setopt(easy_.get(),CURLOPT_TIMEOUT_MS,static_cast<long>( duration_cast<milliseconds>(request_.timeout()) .count())) == CURLE_OK (43 vs. 0) 
```
CURLE code 43 means CURLE_BAD_FUNCTION_ARGUMENT.
If you look into the CURL code:
```
case CURLOPT_TIMEOUT_MS:
arg = va_arg(param, long);
if(arg < 0)
return CURLE_BAD_FUNCTION_ARGUMENT;
data->set.timeout = arg;
break;
```
That means that somehow we are getting the negative number as an argument. After digging into it I found several uninitialized variables, e.g. `timeout` variable, which was providing us with a negative value sometimes.
CURLOPT_TIMEOUT_MS also uses `long` as a type for the timeout …
=> Use std::chrono::duration::count() as an argument for curl_easy_setopt(CURLOPT_TIMEOUT_MS) AND initialize previously uninitialized variables in http.h

3rdparty/bazel-rules-curl/repos.bzl
Should be merged after https://github.com/3rdparty/bazel-rules-curl/pull/15.
Fixes #240.
=> Update curl rules

bazel/eventuals_submodules.bzl, bazel/external_deps.bzl, bazel/external_repos.bzl, bazel/submodule_repository.bzl
By adding `bazel/external_deps.bzl` , `bazel/external_repos.bzl` , `bazel/eventuals_submodules.bzl` files it's possible to use `eventuals` library without having `3rdparty` and `bazel` directories in the root of the project. The only thing needed is to have rules from `bazel/external_deps.bzl` , `bazel/external_repos.bzl` , `bazel/eventuals_submodules.bzl` being invoked in the `WORKSPACE.bazel` file.
=> Add bazel/external_*.bzl pattern

bazel/submodules.bzl
So that others can override the repository if they want!
We also swapped the default to be 'external = True' so that only the
eventuals 'WORKSPACE.bazel' needs to remember to set it to 'False'.
=> Use 'maybe' with 'submodule_repository'

eventuals/scheduler.cc, eventuals/scheduler.h, eventuals/task.h
Include `.h` files rather than `.hpp` files to match the rename in
https://github.com/3rdparty/stout/pull/45
This is a fixed alternative to #400.
=> Manually update to latest stout

test/BUILD.bazel, test/failure-signal-handler.cc, test/failure-signal-handler.h
Earlier we had absolutely horrible stack trace on `glog` check failure, like in example below:
This PR introduces a convenient [signal handler](https://github.com/google/glog#failure-signal-handler) that will dump useful information when the program crashes on certain signals such as SIGSEGV. The signal handler can be installed by `google::InstallFailureSignalHandler()` from `glog` library.
=> Introduce google failure signal handler

protoc-gen-eventuals/protoc-gen-eventuals.py
It looks like the default codespace formatting settings (which I think
should use yapf) disagree with dev-tools as to how this should be
formatted: we should look into how to make the dev-tools style and the
VS Code autoformatter agree.
=> More python formatting to unblock dev-tools

.github/workflows/update-eventuals-tutorial.yml, scripts/update-eventuals-git-repository.sh
This PR adds `.github/workflows/update-eventuals.yml` script which calls PR-bot job for updating eventuals in `3rdparty/eventuals-tutorial`.
NOTE: before merging we should merge [this](https://github.com/3rdparty/dev-tools/pull/47) PR in `3rdparty/dev-tools`, change branch to `main` in `.github/workflows/update-eventuals.yml` and merge [this](https://github.com/3rdparty/eventuals-tutorial/pull/12) PR in `3rdparty/eventuals-tutorial`.
=> PR-bot which updates eventuals in '3rdparty/eventuals-tutorial'

.github/workflows/update-eventuals-tutorial.yml
This PR adds an additional input parameter `repo` to juliangruber/approve-pull-request-action@v1.1.1 as well as updates token in order to use another bot for the pr auto-approve.
=> Add additional 'repo' input for pr auto-approve action

bazel/deps.bzl, bazel/repos.bzl
Since we have [`bazelified`](https://github.com/3rdparty/bazel-rules-expected.git) `expected` [repo](https://github.com/TartanLlama/expected.git), now we can make eventuals also depend on this library too.
=> Add 'expected' dependency for eventuals

Dockerfile.dazel
Reverts 3rdparty/eventuals#413 since the signing key issue appears to be fixed.
=> Revert "Fix Dazel build"

eventuals/dns-resolver.h, eventuals/filesystem.h
Removes half the methods with this change.
=> Refactor: Set EventLoop as the last argument in FileSystem and DNSResolver methods

eventuals/http.h
Since we use WIN32_LEAN_AND_MEAN we also do not need to order our includes in a specific way.
=> Use 'absl::StripAsciiWhitespace' to trim strings in eventuals/http.h

eventuals/type-check.h, test/type-check.cc
Specifically, make this code pattern compile:
```c++
auto Method() {
return ::eventuals::TypeCheck<std::unique_ptr<const MyType>>(
::eventuals::Then([]() {
std::unique_ptr<MyType> ptr = std::make_unique<MyType>();
// Return a non-const ptr that can be assigned to const ptr.
return ptr;
})
);
}
```
Add a bunch of const-conversion tests.
=> Make `TypeCheck` work when mixing constness

eventuals/type-check.h, test/type-check.cc
Reverts 3rdparty/eventuals#441
#441 incorrectly made the following code compile:
```c++
TEST(TypeCheck, MutableVarConstReturnTypeMutableValue) {
std::unique_ptr<int> result = *TypeCheck<std::unique_ptr<const int>>(
Then([&]() -> std::unique_ptr<int> { return std::make_unique<int>(4); }));
EXPECT_EQ(4, *result);
*result = 5;
EXPECT_EQ(5, *result);
}
```
This was because I incorrectly thought that `TypeCheck` was similar to declaring a return type, but it's not: the type specified in the `TypeCheck` doesn't affect the type seen by callers.
See discussion in https://github.com/reboot-dev/respect/pull/570/files/23d26d0b8dc0185b8e6e377b70d2e26fe5c995b5#diff-fa028406a1e7e59d2d16e6fac11b1cd2d15002a9001cd6ff7613fcc614e91926
=> Revert "Make `TypeCheck` work when mixing constness"

.bazelrc, .github/workflows/build_and_test.yml
This should speed up template compilation times and improve
https://github.com/3rdparty/eventuals/issues/275.
This also ensures that clang is used on all platforms. Before this PR,
our CI servers were building with gcc.
=> Compile with clang by default

bazel/repos.bzl, test/BUILD.bazel, test/concurrent/BUILD.bazel, test/grpc/BUILD.bazel
Since 'backward-stacktrace.cc|.h' are completely unrelated to eventuals,
so it makes sense to keep them separate. This PR removes this files. Moreover, [#2](https://github.com/3rdparty/bazel-rules-backward-cpp/pull/2) moves this files to `3rdparty/bazel-rules-backward-cpp` repo. Thus it would be easy to use
that in '3rdparty/eventuals' and 'reboot-dev/respect' repos.
=> Remove 'backward' cc_library target from test/eventuals

.clang-tidy, .clangd, .gitignore, BUILD.bazel, WORKSPACE.bazel
Allows [clangd](https://clangd.llvm.org/) LSP to work in VS Code (or any other IDE/Code Editor that has some kind of a support for clangd).
The output of the added rule can also be used in [clang-tidy](https://clang.llvm.org/extra/clang-tidy/) (which is how https://github.com/3rdparty/eventuals/pull/465 PR was created).
The README in https://github.com/hedronvision/bazel-compile-commands-extractor was especially helpful in the process of setting everything up.
=> clangd and clang-tidy initial support

BUILD.bazel
After I found how to fix my build [here](https://github.com/3rdparty/eventuals/issues/471), I went ahead and tried putting `...` as a target for refresh_compile_commands rule - it worked. Now there's no reason for us to have separate `refresh_cc` rules for Windows and other platforms.
=> Use ... as a target for compile commands extractor

BUILD.bazel
The last down-stream uses of these targets are being removed in
https://github.com/reboot-dev/respect/pull/672.
Fixes https://github.com/3rdparty/eventuals/issues/473
=> Remove deprecated build targets

bazel/malloc.bzl, eventuals/BUILD.bazel, test/BUILD.bazel, test/grpc/BUILD.bazel
This is recommended here: https://github.com/bazelbuild/bazel/issues/818#issuecomment-180362316
But more importantly, this fixes issues when trying to include eventuals
in targets that are built as shared libraries.
Fixes https://github.com/3rdparty/eventuals/issues/470.
=> Prefer to use `malloc` to override malloc

README.md
The intended condition seems to need a `!`; not important to the content, but I won't be able to unsee it 🙃
=> Update example condition in README

.bazelrc
This should hopefully reduce the number of timeouts we're seeing when
running builds from systems in various locations. e.g. per
https://github.com/reboot-dev/respect/issues/698#issuecomment-1195302008
this should allow builds run from GitHub Codespaces (and presumably
GitHub Actions Runner) to access a remote cache storage bucket that's
closer to that system, which should hopefully reduce network latency and
improve reliability.
Should improve https://github.com/3rdparty/eventuals/issues/293.
TESTED=`dazel test //...` works from my codespace.
=> Switch bazel remote cache to a multi-region bucket

eventuals/pipe.h
I sure would love to be able to break a loop I have (independent of a `Pipe`) on the condition that the pipe has been closed. I.e., I'd love to write code like this:
```c++
Repeat()
>> Map([]{ ... })
>> Until([&this]() {
return pipe_.IsClosed();
})
>> Loop();
```
Before this commit, it does not seem possible as `Pipe<>::is_closed_` is not accessible. This commit adds a public eventuals wrapped accessor to expose this value and allow for the above code.
=> Add `IsClosed` to `Pipe`

eventuals/BUILD.bazel, eventuals/collect.h, eventuals/protobuf/BUILD.bazel, eventuals/protobuf/collectors.h, eventuals/type-traits.h, test/collect.cc, test/filter.cc, test/flat-map.cc, test/protobuf/BUILD.bazel, test/protobuf/collect.cc
Makes `Collect()` more generic and allows others to extend its functionality to other collections by implementing their own `eventuals::Collector`.
=> Add an option for users to overload an eventuals::Collector for Collect()

eventuals/collect.h, test/collect.cc, test/concurrent/emit-fail-interrupt.cc, test/concurrent/emit-interrupt-fail.cc, test/concurrent/emit-interrupt-stop.cc, test/concurrent/emit-stop-interrupt.cc, test/concurrent/fail-before-start.cc, test/concurrent/fail-or-stop.cc, test/concurrent/fail.cc, test/concurrent/flat-map.cc, test/concurrent/interrupt-fail-or-stop.cc, test/concurrent/interrupt-fail.cc, test/concurrent/interrupt-stop.cc, test/concurrent/interrupt-success.cc, test/concurrent/moveable.cc, test/concurrent/stop-before-start.cc, test/concurrent/stop.cc, test/concurrent/stream-fail.cc, test/concurrent/stream-stop.cc, test/concurrent/success.cc, test/filter.cc, test/flat-map.cc, test/generator.cc, test/pipe.cc, test/protobuf/collect.cc, test/range.cc, test/static-thread-pool.cc, test/take.cc, test/transformer.cc, test/type-check.cc
Addresses https://github.com/3rdparty/eventuals/issues/486.
There's one specific test in `test/flat-map.cc` that worked before because we put the collection into the context of the `Loop`, that's why we could access the collection inside the `.stop` function. With the current implementation this doesn't work (though it's possible to make it work, but it would go against what we currently have in other `Eventuals` (No `Stop` method passes anything into the `k.Stop()`)). What are your thoughts on this test, @benh?
For now, I commented out this test.
=> Erase Collect's collection type

eventuals/take.h, test/take.cc
Making '_TestRange' continuation be inherited from
'TypeErasedStream' helps us avoid situations which
can block us for ever. Generally speaking now
'TakeRange' decides either we should continue
pulling from the stream or it's all done and we can
just continue processing given pipeline. This PR
also includes some minor code changes like renaming
some functions.
=> Make '_TestRange' continuation act as a stream

eventuals/event-loop.cc, eventuals/grpc/server.cc, eventuals/http.h, test/conditional.cc, test/eventual.cc, test/lock.cc, test/static-thread-pool.cc, test/stream.cc, test/then.cc, test/timer.cc
Direct initialization is simpler than copy initialization, and shorter
(you don't need to specify the type / constructor name on both the LHS
and RHS of the initialization line).
These two forms should have the same effect in C++17:
https://stackoverflow.com/a/41891708 pre-C++17, direct initialization
was typically faster / simpler (since copy initialization might incur
copies).
=> Construct objects using direct initialization

eventuals/callback.h, eventuals/event-loop.h, eventuals/filesystem.h, eventuals/grpc/logging.h, eventuals/http.h, eventuals/rsa.h, eventuals/static-thread-pool.h, eventuals/x509.h
According to [clang-tidy](https://clang.llvm.org/extra/clang-tidy/checks/modernize/use-equals-default.html):
```
The explicitly defaulted function declarations enable more opportunities in optimization,
because the compiler might treat explicitly defaulted functions as trivial.
```
=> Use `= default` where applicable. Add missing include in `eventuals/grpc/logging.h` 

eventuals/static-thread-pool.h
Prevents copying `Requirements'` `std::string` field.
=> `std::move` `Requirements` when constructing `Schedulable`

eventuals/callback.h, eventuals/do-all.h, eventuals/head.h, eventuals/iterate.h, eventuals/map.h, eventuals/reduce.h, eventuals/until.h, protoc-gen-eventuals/templates/eventuals.cc.j2, test/grpc/helloworld.eventuals.cc, test/stream.cc
Also fixes a bug where the return value must be default constructible
by making the first item in the 'std::variant' be an 'Undefined'.
=> Fix 'DoAll()' so each eventual has own 'Scheduler::Context'

eventuals/BUILD.bazel, eventuals/request-response-channel.h, test/BUILD.bazel, test/request-response-channel.cc
This PR adds 'RequestResponseChannel' which is generally
speaking a synchronized "pipe in a pipe" for handling
requests and responses. So it guarantees that for every
request that is written we read a response in order.
=> Introduce 'RequestResponseChannel'

eventuals/BUILD.bazel, eventuals/on-begin.h, eventuals/on-ended.h, test/BUILD.bazel, test/on-begin.cc, test/on-ended.cc
Adds combinators for doing computation (possibly asynchronously) when a stream/generator begins or ends.
Fixes #527
=> Add combinators 'OnBegin' and 'OnEnded'

eventuals/event-loop.cc, eventuals/event-loop.h, eventuals/grpc/BUILD.bazel, eventuals/grpc/client.h, eventuals/grpc/completion-thread-pool.cc, eventuals/grpc/completion-thread-pool.h, eventuals/grpc/server.cc, eventuals/grpc/server.h, eventuals/promisify.h, test/event-loop-test.h, test/flat-map.cc, test/grpc/BUILD.bazel, test/grpc/cancelled-by-client.cc, test/grpc/cancelled-by-server.cc, test/grpc/deadline.cc, test/grpc/death-client.cc, test/grpc/greeter-server.cc, test/grpc/multiple-hosts.cc, test/grpc/ordering-dependent-test.h, test/grpc/server-death-test.cc, test/grpc/server-unavailable.cc, test/grpc/streaming.cc, test/grpc/unary.cc, test/grpc/unimplemented.cc, test/http.cc, test/signal.cc, test/timer.cc
NOTE: this PR has multiple smaller commits to make it easier to see the progression of changes.
Often when writing tests with gRPC you want to deterministically ensure some ordering of events to test a particular code path. You can do so by using a 'TestingCompletionThreadPool' which only has a single thread that can be paused so as to ensure that no computation takes place until a particular time or you can wait on it until there is no more work to be done.
=> Introduce 'TestingCompletionThreadPool'

eventuals/event-loop.h, eventuals/interrupt.h, eventuals/promisify.h, eventuals/static-thread-pool.h, test/flat-map.cc
This commit also introduces a 'Run()' function which 'operator*' now
calls instead (since 'operator*' is just syntactic sugar).
=> Introduce 'EventLoop::RunOnce()' and refactor 'operator*' to use

test/grpc/BUILD.bazel, test/grpc/cancelled-by-client-no-finish.cc
In particular, you can either '::grpc::ClientContext::TryCancel()' or
just destruct '::grpc::ClientContext:: and grpc will "do the right
thing".
=> Add tests which ensure clients don't need to 'Finish()'

eventuals/os.h, test/BUILD.bazel, test/os.cc
This PR implements 'Thread' class which has the possibility
to run the task in another thread as well as setting stack
size with specific value. For now this stuff works only on
`Linux` and `macOS`. For `Windows` the implementation might
be added in the future.
=> Thread implementation

.github/workflows/update-eventuals-tutorial.yml
Our workflow fails on brew install on ubuntu.
https://github.com/3rdparty/eventuals/actions/runs/4793249892/jobs/8525533880
`/home/runner/work/_temp/f1046819-d924-4620-aca9-f6872b5e2677.sh: line 1: brew: command not found`
At the same time, we are using ubuntu brew in some other places using another signature.
This PR should fix the workflow brew error.
=> Fix brew installation for ubuntu on workflow

eventuals/expected.h, eventuals/os.h
* Add explicit using for operator* to `eventuals::expected`.
* Make some LOG(WARNING) be LOG(FATAL) so we don't hang forever when there are irrecoverable failures.
=> Minor fixes

eventuals/os.h, test/os.cc
Backtrace is not currently supported for arm mac, but we use it only in cc_test, so we can build the core library.
=> Add arm64 MACH support for os.h

.github/workflows/build_and_test.yml
Due to https://github.com/3rdparty/eventuals/issues/608 the build/test checks are currently broken and actively harmful to our ability to merge PRs. This commit disables them until they've been fixed.
=> Disable build+test checks until they've been fixed

bazel/repos.bzl, eventuals/rsa.h
Should go after that https://github.com/3rdparty/bazel-rules-curl/pull/18
Tested on the host MacOS arm64 machine.
=> Update boringssl with lib_curl

eventuals/concurrent.h, eventuals/event-loop.cc, eventuals/event-loop.h, eventuals/grpc/server.h, eventuals/scheduler.cc, eventuals/scheduler.h, eventuals/static-thread-pool.cc, eventuals/static-thread-pool.h, test/BUILD.bazel, test/concurrent/BUILD.bazel, test/concurrent/concurrent-with-timer.cc, test/concurrent/concurrent.h
Fixes https://github.com/reboot-dev/respect/issues/2951
=> Fix Concurrent deadlock
